spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}

app:
  redirectBaseUrl: http://localhost:8080/fwd/
  maxLength: 10

server:
  error:
    include-stacktrace: never
